// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/vozoo_dsp.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class VozooDspBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  VozooDspBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  VozooDspBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// Process an audio file with the given voice preset.
  ///
  /// Returns 0 on success, -1 on read error, -2 on write error.
  int process_file(
    ffi.Pointer<ffi.Char> input_path,
    ffi.Pointer<ffi.Char> output_path,
    int preset_id,
  ) {
    return _process_file(
      input_path,
      output_path,
      preset_id,
    );
  }

  late final _process_filePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>,
              ffi.Int)>>('process_file');
  late final _process_file = _process_filePtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int)>();
}
